---
title: "Trends in Hiring using LinkedIn Data 2015-2019"
author: Niklas Lollo
date: Sys.Date()
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(lubridate)
library(tidytext)

# Load data
dat <- read_csv("../temp_datalab_records_linkedin_company.csv")
```

```{r data cleaning}
# Remove & and combine fields
dat <- dat %>%
  mutate(
    industry = str_replace_all(industry, "&", "and"),
    industry = str_replace_all(industry, "amp;", "")
  )
# table(dat$industry)
```

```{r which industries are hiring}
# Which industries are best represented in the dataset?
## 1. Basic: Display count by industry
dat %>% 
  count(industry, sort = T, name = "industry_total")
# Add count to dataset
dat <- dat %>%
  add_count(industry, name = "industry_total") %>%
  add_count(company_name, name = "company_total") %>%
  add_count(company_name, industry, name = "industry_company_total")

## 2. Proportional by # of employees
dat <- dat %>%
  group_by(company_name) %>%
  mutate(
    avg_employee_ct = mean(employees_on_platform, na.rm=T)
  ) %>%
  ungroup

summary(dat$employees_on_platform)
# need to filter for startups (<10)

# Suprising number of jobs compared to employees
surprise <- dat %>%
  filter(avg_employee_ct >=10) %>%
  group_by(company_name, industry) %>%
  mutate(
    ind_comp_emp_ratio = industry_company_total/avg_employee_ct
  ) %>%
  ungroup %>%
  group_by(industry)%>%
  summarize(
    mean_ratio = mean(ind_comp_emp_ratio, na.rm=T)
  ) %>% ungroup %>%
  arrange(desc(mean_ratio)) 
head(surprise)
# Writing and Editing by far and away the most

# Display
surprise %>%
  filter(mean_ratio >7) %>%
  ggplot() +
  geom_point(aes(mean_ratio, fct_reorder(industry, mean_ratio))) +
  theme_classic() +
  xlab("Ratio of Jobs to Employees") + 
  theme(axis.title.y = element_blank()) +
  ggtitle(label = "Writing and Editing is hiring!")
  
```


```{r by year}
#Companies that hire at different times than the rest of their industry
dat %>%
  # Company/ industry at particular time
  add_count(industry, company_name, year(date_added), month(date_added), name= "company_industry_time") %>%
  # Industry at particular time
  add_count(industry, year(date_added), month(date_added), name = "industry_time") %>%
  # Compare difference
  group_by(company_name, industry) %>%
  mutate(
    ind_avg = mean(industry_time, na.rm=T),
    com_avg = mean(company_industry_time, na.rm=T),
    pctdiff_from_avg = (company_industry_time - com_avg)/(industry_time - ind_avg) *100
  ) %>%
  ungroup -> dat

dat %>%  
  filter(industry == "Apparel and Fashion" & 
           pctdiff_from_avg > 25 &
           avg_employee_ct > 150) %>%
  ggplot() +
  geom_point(aes(x = date_added, y= pctdiff_from_avg, color = company_name)) +
    theme_classic() +
  ggtitle("Apparel companies that have hiring spikes",
          subtitle = "Compared to industry average at that time.") +
  ylab("% diff from avg") +
  theme(
    axis.title.x = element_blank(),
    legend.title = element_blank()
  )
```
